// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MEL.Flex")>]
[<assembly: AssemblyProductAttribute("MEL.Flex")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-04-08T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","2d3b2327f615a586dd3c86d60fce730a28bcd4ec")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MEL.Flex"
    let [<Literal>] AssemblyProduct = "MEL.Flex"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-04-08T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "2d3b2327f615a586dd3c86d60fce730a28bcd4ec"
